//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantBooking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_ID { get; set; }
        public int User_ID { get; set; }
        public int Table { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
    
        public virtual Auth Auth { get; set; }
    }
}
