//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantBooking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCoupon
    {
        public int OrderCoupon_ID { get; set; }
        public int Coupon_ID { get; set; }
        public int Order_ID { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Order Order { get; set; }
    }
}
